INSERT INTO item (id, name, type, usable, description) VALUES
(1, 'Baume d’Écorce', 'consumable', 1, 'Réduit les dégâts des 4 premiers assauts.'),
(2, 'Graine d’Enchevêtrement', 'consumable', 1, 'Diminue l’Habileté de l’ennemi de 2 au début d’un combat.'),
(3, 'Flûte', 'misc', 0, 'Flûte non magique.'),
(4, 'Flûte de Pan', 'misc', 0, 'Instrument offert par un satyre.'),
(5, 'Pierre percée', 'misc', 0, 'Permet de voir à travers les illusions.'),
(6, 'Repas', 'consumable', 1, 'Rend 4 points d’Endurance.'),
(7, 'Couronne Thym-Primevères', 'equipment', 0, 'Permet de voir l’invisible.'),
(8, 'Couronne Trèfles-Pâquerettes', 'equipment', 0, 'Protège de la magie des fées.'),
(9, 'Baume d’Habileté', 'consumable', 1, 'Restaure l’Habileté au total de départ.'),
(10, 'Baume d’Endurance', 'consumable', 1, 'Restaure l’Endurance au total de départ.'),
(11, 'Baume de Chance', 'consumable', 1, 'Restaure la Chance au total de départ.'),
(12, 'Décoction de racines', 'consumable', 1, 'Rend 8 Endurance, +1 Habileté, -3 Ivresse.'),
(13, 'Poison végétal', 'consumable', 1, 'Ajoute +3 dégâts par coup au prochain combat.'),
(14, 'Harpe', 'misc', 0, 'Instrument trouvé dans une hutte.'),
(15, 'Gourde de vin', 'consumable', 1, 'Augmente Ivresse de 4 et Endurance de 6.'),
(16, 'Miel', 'consumable', 1, 'Rend 4 Endurance et +1 Chance.'),
(17, 'Trèfles à quatre feuilles', 'misc', 0, 'Augmente la Chance à 13.'),
(18, 'Pièce d’or', 'currency', 0, 'Monnaie.');